#!/usr/bin/env bash
#
# The gate. Everything CI asserts, runnable on a laptop with one command —
# because a gate a developer cannot run locally is a gate they discover in a
# pull request, ten minutes at a time.
#
#   bash scripts/check.sh            # analyze + tests + l10n drift, all packages
#   bash scripts/check.sh --build    # ...and a release web build of each app
#   bash scripts/check.sh rms_waiter # one package only
#
# .github/workflows/ci.yml runs these same steps. When you add a step, add it
# here, so the two cannot drift.

set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# rms_core first: the four apps depend on it by path, so a break here is a
# break everywhere, and hearing about it once beats hearing it five times.
ALL_PACKAGES=(packages/rms_core rms_waiter rms_manager rms_driver rms_customer)
APPS=(rms_waiter rms_manager rms_driver rms_customer)

WITH_BUILD=0
SELECTED=()
for arg in "$@"; do
  case "$arg" in
    --build) WITH_BUILD=1 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) SELECTED+=("$arg") ;;
  esac
done
if [ ${#SELECTED[@]} -gt 0 ]; then
  PACKAGES=("${SELECTED[@]}")
else
  PACKAGES=("${ALL_PACKAGES[@]}")
fi

if ! command -v flutter >/dev/null 2>&1; then
  echo "flutter is not on PATH." >&2
  echo "Add your SDK, e.g.: export PATH=\"\$PATH:\$HOME/flutter/bin\"" >&2
  exit 127
fi

BOLD=''; RED=''; GREEN=''; DIM=''; RESET=''
if [ -t 1 ]; then
  BOLD=$'\033[1m'; RED=$'\033[31m'; GREEN=$'\033[32m'; DIM=$'\033[2m'; RESET=$'\033[0m'
fi

FAILURES=()
step() { printf '%s\n' "${BOLD}==> $*${RESET}"; }
fail() { FAILURES+=("$1"); printf '%s\n' "${RED}FAIL${RESET} $1"; }
ok()   { printf '%s\n' "${GREEN}ok${RESET}   ${DIM}$1${RESET}"; }

# Runs a command in a package, keeping its output only if it fails: a green run
# should be readable at a glance, and a red one should show everything.
run_in() {
  local pkg="$1" label="$2"; shift 2
  local log
  log="$(mktemp)"
  if (cd "$pkg" && "$@") >"$log" 2>&1; then
    ok "$pkg — $label"
    rm -f "$log"
    return 0
  fi
  fail "$pkg — $label"
  sed 's/^/     /' "$log"
  rm -f "$log"
  return 1
}

step "flutter $(flutter --version 2>/dev/null | head -1 | sed 's/^Flutter //')"

for pkg in "${PACKAGES[@]}"; do
  if [ ! -f "$pkg/pubspec.yaml" ]; then
    fail "$pkg — no pubspec.yaml (is that a package in this repo?)"
    continue
  fi

  step "$pkg"
  run_in "$pkg" "pub get" flutter pub get --enforce-lockfile || continue
  run_in "$pkg" "analyze" flutter analyze
  run_in "$pkg" "test" flutter test

  # The generated localisations are committed AND regenerated by every build,
  # so an .arb edited without regenerating leaves a stale file in git that is
  # invisible locally — the next build silently rewrites it. Regenerate and
  # insist git sees nothing.
  if [ -f "$pkg/l10n.yaml" ]; then
    if run_in "$pkg" "gen-l10n" flutter gen-l10n; then
      out_dir="$pkg/$(sed -n 's/^output-dir: *//p' "$pkg/l10n.yaml")"
      if [ -n "${out_dir#$pkg/}" ] && ! git diff --quiet -- "$out_dir"; then
        fail "$pkg — generated localisations are stale; commit the regenerated $out_dir"
        git diff --stat -- "$out_dir" | sed 's/^/     /'
      else
        ok "$pkg — l10n in sync with its .arb files"
      fi
    fi
  fi
done

if [ "$WITH_BUILD" -eq 1 ]; then
  for app in "${APPS[@]}"; do
    step "$app — release web build"
    run_in "$app" "build web --release" flutter build web --release
  done
fi

echo
if [ ${#FAILURES[@]} -eq 0 ]; then
  printf '%s\n' "${GREEN}${BOLD}All checks passed.${RESET}"
  exit 0
fi
printf '%s\n' "${RED}${BOLD}${#FAILURES[@]} check(s) failed:${RESET}"
for f in "${FAILURES[@]}"; do printf '%s\n' "  - $f"; done
exit 1
